---
title: "Lithology_Figures"
output: html_document
date: "2023-07-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Load in packages

```{r}
library(tidyverse)
library(here)
library(janitor)
library(readxl)
library(ggplot2)
```

# Loading in data

```{r}
# data for pie charts
well_lith <- read_excel(here("data/Well Lithology.xlsx"))|>
  clean_names()|>
  select(name, well_name, start_depth, end_depth, condensed_lithology)%>%
  mutate_all(str_to_title)|>
  mutate(start_depth = as.numeric(start_depth),
         end_depth = as.numeric(end_depth))


# Removing NA column
well_lith <- well_lith[-11, , drop = FALSE]

well_lith2 <- read_excel(here("data/Well Lithology.xlsx"), sheet = 2)|>
  clean_names()

# Filter data for Bixby Ranch
bixby_ranch <- well_lith |>
  filter(name == "Bixby Ranch")

# Filter data for Jalama Ranch
jalama_ranch <- well_lith |>
  filter(name == "Jalama Ranch") 

# Filter data for Cojo Ranch
cojo_ranch <- well_lith |>
  filter(name == "Cojo Ranch")

# data for bar charts

well_lith_bar <- read_excel(here("data/Copy of Well Lithology.xlsx"))|>
  clean_names()|>
  select(name, well_name, start_depth, end_depth, segment_depth, condensed_lithology)%>%
  mutate_all(str_to_title)|>
  mutate(start_depth = as.numeric(start_depth),
         end_depth = as.numeric(end_depth),
         segment_depth = as.numeric(segment_depth))

# Filter data for Bixby Ranch
bixby_ranch_bar <- well_lith_bar |>
  filter(name == "Bixby Ranch")

# Filter data for Jalama Ranch
jalama_ranch_bar <- well_lith_bar |>
  filter(name == "Jalama Ranch") 

# Filter data for Cojo Ranch
cojo_ranch_bar <- well_lith_bar |>
  filter(name == "Cojo Ranch")

# Filtering individual wells for Bixby Ranch
low_espada1 <- bixby_ranch_bar |>
  filter(well_name == "Lower Espada Well #1")

up_espada3 <- bixby_ranch_bar |>
  filter(well_name == "Upper Espada Well #3")
  
wood_c4 <- bixby_ranch_bar |>
  filter(well_name == "Wood Canyon Well #4")
  
quail_c <- bixby_ranch_bar |>
  filter(well_name == "Quail Canyon Well")

jalachichi1 <- bixby_ranch_bar |>
  filter(well_name == "Jalachichi Well #1")

tinta1 <- bixby_ranch_bar |>
  filter(well_name == "Tinta #1")

tinta2 <- bixby_ranch_bar |>
  filter(well_name == "Tinta #2")

east_r <- bixby_ranch_bar |>
  filter(well_name == "Ramajal East Well")

vaquero1 <- bixby_ranch_bar |>
  filter(well_name == "Vaquero #1")


#Removing redundant columns
low_espada1 <- low_espada1[-c(3, 4), ]

# Filtering individual wells for Jalama Ranch
vaqueros1 <- jalama_ranch_bar |>
  filter(well_name == "Vaqueros #1")

espada <- jalama_ranch_bar |>
  filter(well_name == "Espada Well")

gaspar1 <- jalama_ranch_bar |>
  filter(well_name == "Gaspar Well #1")

gaspar2 <- jalama_ranch_bar |>
  filter(well_name == "Gaspar Well #2")

venadito1 <- jalama_ranch_bar |>
  filter(well_name == "Venadito Well #1")

venadito2 <- jalama_ranch_bar |>
  filter(well_name == "Venadito Well #2")

escondido1 <- jalama_ranch_bar |>
  filter(well_name == "Escondido Well #1")

escondido2 <- jalama_ranch_bar |>
  filter(well_name == "Escondido Well #2")

escondido3 <- jalama_ranch_bar |>
  filter(well_name == "Escondido Well #3")

escondido4 <- jalama_ranch_bar |>
  filter(well_name == "Escondido Well #4")

escondido5 <- jalama_ranch_bar |>
  filter(well_name == "Escondido Well #5")

# Filtering individual wells for Cojo Ranch
oaks1 <- cojo_ranch_bar |>
  filter(well_name == "Oaks Well #1")

oaks2 <- cojo_ranch_bar |>
  filter(well_name == "Oaks Well #2")

oaks3 <- cojo_ranch_bar |>
  filter(well_name == "Oaks Well #3")

oaks4 <- cojo_ranch_bar |>
  filter(well_name == "Oaks Well #4")

oaks5 <- cojo_ranch_bar |>
  filter(well_name == "Oaks Well #5")

oaks3 <- cojo_ranch_bar |>
  filter(well_name == "Oaks Monitoring Well #3b")

```

# Cojo Ranch Lithology Pie Chart

```{r}
# Define the color palette
color_palette <- c("#808080", "#D2B48C", "#6699CC", "#228B22", "#ADD8E6", "#800000", "#964B00", "#FF00FF")
names(color_palette) <- c("Clay", "Clay, Gravel, Sand", "Clay, Shale", "Shale", "Shale, Gravel, Clay", "Shale, Sand, Clay", "Soil", "Till")

# Count the frequency of items in condensed_lithology column
lithology_freq <- table(cojo_ranch$condensed_lithology)

# Create a data frame with lithology frequencies
df <- data.frame(lithology = names(lithology_freq), freq = as.numeric(lithology_freq))

# Sort the data frame by frequency in descending order
df <- df %>% arrange(desc(freq))

# Calculate the percentage labels based on the sorted data frame
percent_labels <- paste0(round(100 * df$freq / sum(df$freq), 1), "%")

# Add the percent_labels to the data frame
df$percent <- percent_labels

# Create the pie chart with adjusted label positions to avoid overlap
pie_chart_cojo <- ggplot(df, aes(x = "", y = freq, fill = lithology, label = "")) +
  geom_bar(stat = "identity", width = 1, color = "black") +
  coord_polar(theta = "y", start = 0) +
  geom_text(aes(label = percent), position = position_stack(vjust = 0.5), size = 3) +
  scale_fill_manual(values = color_palette, name = "Lithology") +
  theme_void() +
  theme(panel.border = element_blank(),
        plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
        legend.position = "right",
        legend.title = element_text(size = 12, face = "bold"),
        legend.text = element_text(size = 10)) +
  labs(title = "Frequency of Lithologies - Cojo Ranch")

# Display the pie chart
print(pie_chart_cojo)

```


# Jalama Ranch Lithology Pie Chart 

```{r}
# Count the frequency of items in condensed_lithology column
lithology_freq <- table(jalama_ranch$condensed_lithology)

# Create a data frame with lithology frequencies and percentage labels
df <- data.frame(lithology = names(lithology_freq), freq = as.numeric(lithology_freq))

# Calculate the percentage labels
percent_labels <- paste0(round(100 * df$freq / sum(df$freq), 1), "%")
df$percent <- percent_labels

# Sort the data frame by frequency in descending order
df <- df %>% arrange(desc(freq))

# Define the color palette
color_palette <- c("#808080", "#6699CC", "#228B22", "#ADD8E6", "#964B00", "#FF6666", "#E8E8E8", "#FFA500", "#D2691E", "#FDD9A2", "#D8BFD8")
names(color_palette) <- c("Clay", "Clay, Shale", "Shale", "Shale, Gravel, Clay", "Soil", "Adobe, Shale", "Clay, Gravel", "Claystone", "Sand, Gravel", "Sandstone", "Shale, Sandstone")

# Create the pie chart with adjusted label positions to avoid overlap
pie_chart_jalama <- ggplot(df, aes(x = "", y = freq, fill = lithology, label = "")) +
  geom_bar(stat = "identity", width = 1, color = "black") +
  coord_polar(theta = "y", start = 0) +
  geom_text(aes(label = percent), position = position_stack(vjust = 0.5), size = 2.5) +
  scale_fill_manual(values = color_palette, name = "Lithology") +
  theme_void() +
  theme(panel.border = element_blank(),
        plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
        legend.position = "right",
        legend.title = element_text(size = 12, face = "bold"),
        legend.text = element_text(size = 10)) +
  labs(title = "Frequency of Lithologies - Jalama Ranch")

# Display the pie chart
print(pie_chart_jalama)

```



```{r}
color_palette <- c("#808080", "#6699CC", "#228B22", "#ADD8E6", "#964B00", "#FF6666", "#E8E8E8","#FFA500", "#D2691E", "#FDD9A2", "#D8BFD8")
names(color_palette) <- c("Clay", "Clay, Shale", "Shale", "Shale, Gravel, Clay", "Soil", "Adobe, Shale", "Clay, Gravel", "Claystone", "Sand, Gravel", "Sandstone", "Shale, Sandstone")
```

# Bixby Ranch Lithology Pie Chart

```{r}
# Count the frequency of items in condensed_lithology column
lithology_freq <- table(bixby_ranch$condensed_lithology)

# Create a data frame with lithology frequencies and percentage labels
df <- data.frame(lithology = names(lithology_freq), freq = as.numeric(lithology_freq))

# Calculate the percentage labels
percent_labels <- paste0(round(100 * df$freq / sum(df$freq), 1), "%")
df$percent <- percent_labels

# Sort the data frame by frequency in descending order
df <- df %>% arrange(desc(freq))

# Define the color palette
color_palette <- c("#808080", "#228B22", "#964B00", "#FDD9A2", "#6A0DAD", "#FFE135", "#00FF00", "#FF69B4")
names(color_palette) <- c("Clay", "Shale", "Soil", "Sandstone", "Gravel", "Siltstone", "Siltstone, Sandstone", "Soil, Clay")

# Create the pie chart with adjusted label positions to avoid overlap
pie_chart_bixby <- ggplot(df, aes(x = "", y = freq, fill = lithology, label = "")) +
  geom_bar(stat = "identity", width = 1, color = "black") +
  coord_polar(theta = "y", start = 0) +
  geom_text(aes(label = percent), position = position_stack(vjust = 0.5), size = 2.5) +
  scale_fill_manual(values = color_palette, name = "Lithology") +
  theme_void() +
  theme(panel.border = element_blank(),
        plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
        legend.position = "right",
        legend.title = element_text(size = 12, face = "bold"),
        legend.text = element_text(size = 10)) +
  labs(title = "Frequency of Lithologies - Bixby Ranch")

# Display the pie chart
print(pie_chart_bixby)

```
```{r}
# Bixby 
color_palette <- c("#808080", "#228B22", "#964B00", "#FDD9A2", "#6A0DAD", "#FFE135", "#FFA500", "#FF69B4" )
names(color_palette) <- c("Clay", "Shale", "Soil", "Sandstone", "Gravel", "Siltstone", "Siltstone, Sandstone", "Soil, Clay")
```

```{r}
# Jalama
color_palette <- c("#808080", "#6699CC", "#228B22", "#ADD8E6", "#964B00", "#FF6666", "#E8E8E8","#FFA500", "#D2691E", "#FDD9A2", "#D8BFD8")
names(color_palette) <- c("Clay", "Clay, Shale", "Shale", "Shale, Gravel, Clay", "Soil", "Adobe, Shale", "Clay, Gravel", "Claystone", "Sand, Gravel", "Sandstone", "Shale, Sandstone")
```

```{r}
# Cojo
color_palette <- c("#808080", "#D2B48C", "#6699CC", "#228B22", "#ADD8E6", "#800000", "#964B00", "#FF00FF")
names(color_palette) <- c("Clay", "Clay, Gravel, Sand", "Clay, Shale", "Shale", "Shale, Gravel, Clay", "Shale, Sand, Clay", "Soil", "Till")
```

```{r}
# total
color_palette <- c("#808080", "#D2B48C", "#6699CC", "#228B22", "#ADD8E6", "#800000", "#964B00", "#FF00FF", "#FF6666", "#E8E8E8","#FFA500", "#D2691E", "#FDD9A2", "#D8BFD8", "#6A0DAD", "#FFE135", "#00FF00", "#FF69B4" )
names(color_palette) <- c("Clay", "Clay, Gravel, Sand", "Clay, Shale", "Shale", "Shale, Gravel, Clay", "Shale, Sand, Clay", "Soil", "Till", "Adobe, Shale", "Clay, Gravel", "Claystone", "Sand, Gravel", "Sandstone", "Shale, Sandstone", "Gravel", "Siltstone", "Siltstone, Sandstone", "Soil, Clay")

```

# All Ranches Lithology Pie Chart

```{r}
# Count the frequency of items in condensed_lithology column
lithology_freq <- table(well_lith$condensed_lithology)

# Create a data frame with lithology frequencies and percentage labels
df <- data.frame(lithology = names(lithology_freq), freq = as.numeric(lithology_freq))

# Calculate the percentage labels
percent_labels <- paste0(round(100 * df$freq / sum(df$freq), 1), "%")
df$percent <- percent_labels

# Sort the data frame by frequency in descending order
df <- df %>% arrange(desc(freq))

# Define the color palette
color_palette <- c("#808080", "#D2B48C", "#6699CC", "#228B22", "#ADD8E6", "#800000", "#964B00", "#FF00FF", "#FF6666", "#E8E8E8", "#FFA500", "#D2691E", "#FDD9A2", "#D8BFD8", "#6A0DAD", "#FFE135", "#00FF00", "#FF69B4")
names(color_palette) <- c("Clay", "Clay, Gravel, Sand", "Clay, Shale", "Shale", "Shale, Gravel, Clay", "Shale, Sand, Clay", "Soil", "Till", "Adobe, Shale", "Clay, Gravel", "Claystone", "Sand, Gravel", "Sandstone", "Shale, Sandstone", "Gravel", "Siltstone", "Siltstone, Sandstone", "Soil, Clay")

# Create the pie chart with adjusted label positions to avoid overlap
pie_chart_tot <- ggplot(df, aes(x = "", y = freq, fill = lithology, label = "")) +
  geom_bar(stat = "identity", width = 1, color = "black") +
  coord_polar(theta = "y", start = 0) +
  geom_text(aes(label = percent), position = position_stack(vjust = 0.5), size = 2.5) +
  scale_fill_manual(values = color_palette, name = "Lithology") +
  theme_void() +
  theme(panel.border = element_blank(),
        plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
        legend.position = "right",
        legend.title = element_text(size = 12, face = "bold"),
        legend.text = element_text(size = 10)) +
  labs(title = "Frequency of Lithologies - All Ranches")

# Display the pie chart
print(pie_chart_tot)

```


```{r}
color_palette <- c("#808080",
                   "#D2B48C",
                   "#6699CC",
                   "#228B22",
                   "#ADD8E6",
                   "#800000",
                   "#964B00",
                   "#FF00FF",
                   "#FF6666",
                   "#E8E8E8",
                   "#FFA500",
                   "#D2691E",
                   "#FDD9A2",
                   "#D8BFD8",
                   "#6A0DAD",
                   "#FFE135",
                   "#00FF00",
                   "#FF69B4")
names(color_palette) <- c("Clay", "Clay, Gravel, Sand", "Clay, Shale", "Shale", "Shale, Gravel, Clay", "Shale, Sand, Clay", "Soil", "Till", "Adobe, Shale", "Clay, Gravel", "Claystone", "Sand, Gravel", "Sandstone", "Shale, Sandstone", "Gravel", "Siltstone", "Siltstone, Sandstone", "Soil, Clay")
```



```{r}
color_palette_bar <- c("#808080","#808080", "#D2B48C", "#6699CC", "#228B22", "#228B22", "#228B22", "#228B22", "#ADD8E6", "#800000", "#964B00", "#FF00FF", "#FF6666", "#E8E8E8", "#FFA500", "#D2691E", "#FDD9A2", "#FDD9A2", "#FDD9A2", "#FDD9A2", "#D8BFD8", "#6A0DAD", "#FFE135", "#00FF00", "#FF69B4", "#FF0000")
names(color_palette_bar) <- c("Clay", "Clay2", "Clay, Gravel, Sand", "Clay, Shale", "Shale", "Shale2", "Shale3", "Shale4", "Shale, Gravel, Clay", "Shale, Sand, Clay", "Soil", "Till", "Adobe, Shale", "Clay, Gravel", "Claystone", "Sand, Gravel", "Sandstone", "Sandstone2", "Sandstone3", "Sandstone4", "Shale, Sandstone", "Gravel", "Siltstone", "Siltstone, Sandstone", "Soil, Clay", "Na")

```

# Cojo Bar Graphs
```{r fig.width = 3, fig.height = 3}

# Oaks 1 plot
ggplot(oaks1, aes(fill = condensed_lithology, y = segment_depth, x = well_name)) + 
  geom_bar(position = 'stack', stat = 'identity') +
  scale_fill_manual(values = color_palette_bar) +
  labs(x = "Well Name", y = "Well Depth (Ft)", fill = "Lithology") +
  theme_classic() +
  theme(legend.box = "horizontal", legend.box.just = "center")+
  scale_y_continuous(breaks = scales::pretty_breaks(n = 8),       
                     labels = scales::comma,limits = c(0, 250), expand = c(0, 0))

# Oaks 2 plot
# Reorder the levels in condensed_lithology variable
oaks2$condensed_lithology <- factor(oaks2$condensed_lithology,
                                    levels = c("Shale2", "Clay", "Shale", "Soil"))


ggplot(oaks2, aes(fill = condensed_lithology, y = segment_depth, x = well_name)) + 
  geom_bar(position = 'stack', stat = 'identity') +
  scale_fill_manual(values = color_palette_bar) +
  labs(x = "Well Name", y = "Well Depth (Ft)", fill = "Lithology") +
  theme_classic() +
  theme(legend.box = "horizontal", legend.box.just = "center")+
  scale_y_continuous(breaks = scales::pretty_breaks(n = 8),       
                     labels = scales::comma,limits = c(0, 400), expand = c(0, 0))+
  scale_fill_discrete(breaks = "Clay","Shale","Soil")



```

# Jalama Bar Graph

```{r fig.width = 15, fig.height = 10}
ggplot(jalama_ranch_bar, aes(fill = condensed_lithology, y = segment_depth, x = well_name)) + 
  geom_bar(position = 'stack', stat = 'identity') +
  scale_fill_manual(values = color_palette_bar)
```

```{r fig.width = 15, fig.height = 10}
ggplot(bixby_ranch_bar, aes(fill=condensed_lithology, y=segment_depth, x=well_name)) + 
  geom_bar(position='stack', stat='identity')
```



